
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  PrismaClientKnownRequestError,
  PrismaClientUnknownRequestError,
  PrismaClientRustPanicError,
  PrismaClientInitializationError,
  PrismaClientValidationError,
  getPrismaClient,
  sqltag,
  empty,
  join,
  raw,
  skip,
  Decimal,
  Debug,
  objectEnumValues,
  makeStrictEnum,
  Extensions,
  warnOnce,
  defineDmmfProperty,
  Public,
  getRuntime,
  createParam,
} = require('./runtime/wasm-engine-edge.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = PrismaClientKnownRequestError;
Prisma.PrismaClientUnknownRequestError = PrismaClientUnknownRequestError
Prisma.PrismaClientRustPanicError = PrismaClientRustPanicError
Prisma.PrismaClientInitializationError = PrismaClientInitializationError
Prisma.PrismaClientValidationError = PrismaClientValidationError
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = sqltag
Prisma.empty = empty
Prisma.join = join
Prisma.raw = raw
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = Extensions.getExtensionContext
Prisma.defineExtension = Extensions.defineExtension

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}





/**
 * Enums
 */
exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.DeviceScalarFieldEnum = {
  macAddress: 'macAddress',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SensorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  deviceMac: 'deviceMac',
  createdAt: 'createdAt'
};

exports.Prisma.TelemetryScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  deviceMac: 'deviceMac',
  sensorId: 'sensorId',
  wifiRssi: 'wifiRssi',
  uptimeSec: 'uptimeSec',
  sensorType: 'sensorType',
  measurementType: 'measurementType',
  unit: 'unit',
  value: 'value'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  Device: 'Device',
  Sensor: 'Sensor',
  Telemetry: 'Telemetry'
};
/**
 * Create the Client
 */
const config = {
  "generator": {
    "name": "client",
    "provider": {
      "fromEnvVar": null,
      "value": "prisma-client-js"
    },
    "output": {
      "value": "D:\\ESP32\\esp-heating-backend\\prisma\\generated-client",
      "fromEnvVar": null
    },
    "config": {
      "engineType": "library"
    },
    "binaryTargets": [
      {
        "fromEnvVar": null,
        "value": "windows",
        "native": true
      }
    ],
    "previewFeatures": [],
    "sourceFilePath": "D:\\ESP32\\esp-heating-backend\\prisma\\schema.prisma",
    "isCustomOutput": true
  },
  "relativeEnvPaths": {
    "rootEnvPath": "../../.env",
    "schemaEnvPath": "../../.env"
  },
  "relativePath": "..",
  "clientVersion": "6.19.3",
  "engineVersion": "c2990dca591cba766e3b7ef5d9e8a84796e47ab7",
  "datasourceNames": [
    "db"
  ],
  "activeProvider": "postgresql",
  "postinstall": false,
  "inlineDatasources": {
    "db": {
      "url": {
        "fromEnvVar": "DATABASE_URL",
        "value": null
      }
    }
  },
  "inlineSchema": "datasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_URL\")\n}\n\ngenerator client {\n  provider = \"prisma-client-js\"\n  output   = \"./generated-client\"\n}\n\n// 1. Az ESP32 eszközök táblája\nmodel Device {\n  macAddress  String      @id // Az ESP32 egyedi MAC címe\n  name        String? // Pl. \"Kazánház ESP32\"\n  createdAt   DateTime    @default(now())\n  updatedAt   DateTime    @updatedAt\n  sensors     Sensor[]\n  telemetries Telemetry[]\n}\n\n// 2. A DS18B20 szenzorok táblája (így nevesíthetőek a körök)\nmodel Sensor {\n  id          String      @id // A szenzor gyári 16 karakteres azonosítója\n  name        String? // Pl. \"Konyha előremenő\", \"Nappali visszatérő\"\n  deviceMac   String // Melyik ESP32-re van kötve fizikalag\n  device      Device      @relation(fields: [deviceMac], references: [macAddress], onDelete: Cascade)\n  createdAt   DateTime    @default(now())\n  telemetries Telemetry[]\n}\n\n// 3. A nyers mérési adatok (ide ömlik majd a percenkénti adat)\nmodel Telemetry {\n  id              BigInt   @id @default(autoincrement()) // BigInt a rengeteg adat miatt\n  createdAt       DateTime @default(now())\n  deviceMac       String\n  device          Device   @relation(fields: [deviceMac], references: [macAddress], onDelete: Cascade)\n  sensorId        String\n  sensor          Sensor   @relation(fields: [sensorId], references: [id], onDelete: Cascade)\n  wifiRssi        Int\n  uptimeSec       Int\n  sensorType      String // \"DS18B20\"\n  measurementType String // \"temperature\"\n  unit            String // \"C\"\n  value           Float // Pl. 23.55\n\n  @@index([createdAt]) // Idő alapú grafikonok gyorsításához\n  @@index([deviceMac, sensorId])\n}\n",
  "inlineSchemaHash": "fd822b0e46d3d9835255162c3b233277b7238f0f7e396d13ba5e13813887c32a",
  "copyEngine": true
}
config.dirname = '/'

config.runtimeDataModel = JSON.parse("{\"models\":{\"Device\":{\"fields\":[{\"name\":\"macAddress\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"name\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"createdAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"updatedAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"sensors\",\"kind\":\"object\",\"type\":\"Sensor\",\"relationName\":\"DeviceToSensor\"},{\"name\":\"telemetries\",\"kind\":\"object\",\"type\":\"Telemetry\",\"relationName\":\"DeviceToTelemetry\"}],\"dbName\":null},\"Sensor\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"name\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"deviceMac\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"device\",\"kind\":\"object\",\"type\":\"Device\",\"relationName\":\"DeviceToSensor\"},{\"name\":\"createdAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"telemetries\",\"kind\":\"object\",\"type\":\"Telemetry\",\"relationName\":\"SensorToTelemetry\"}],\"dbName\":null},\"Telemetry\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"BigInt\"},{\"name\":\"createdAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"deviceMac\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"device\",\"kind\":\"object\",\"type\":\"Device\",\"relationName\":\"DeviceToTelemetry\"},{\"name\":\"sensorId\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"sensor\",\"kind\":\"object\",\"type\":\"Sensor\",\"relationName\":\"SensorToTelemetry\"},{\"name\":\"wifiRssi\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"uptimeSec\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"sensorType\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"measurementType\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"unit\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"value\",\"kind\":\"scalar\",\"type\":\"Float\"}],\"dbName\":null}},\"enums\":{},\"types\":{}}")
defineDmmfProperty(exports.Prisma, config.runtimeDataModel)
config.engineWasm = {
  getRuntime: async () => require('./query_engine_bg.js'),
  getQueryEngineWasmModule: async () => {
    const loader = (await import('#wasm-engine-loader')).default
    const engine = (await loader).default
    return engine
  }
}
config.compilerWasm = undefined

config.injectableEdgeEnv = () => ({
  parsed: {
    DATABASE_URL: typeof globalThis !== 'undefined' && globalThis['DATABASE_URL'] || typeof process !== 'undefined' && process.env && process.env.DATABASE_URL || undefined
  }
})

if (typeof globalThis !== 'undefined' && globalThis['DEBUG'] || typeof process !== 'undefined' && process.env && process.env.DEBUG || undefined) {
  Debug.enable(typeof globalThis !== 'undefined' && globalThis['DEBUG'] || typeof process !== 'undefined' && process.env && process.env.DEBUG || undefined)
}

const PrismaClient = getPrismaClient(config)
exports.PrismaClient = PrismaClient
Object.assign(exports, Prisma)

